parameters:
    database_driver:   mysql
    database_host:     localhost
    database_port:     ~
    database_name:     MY_PROJECT
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
